/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function addAcc(institutionName: string, accountName: string, industry: Industry, bucketId: number | null) {
    return invoke()<number>("add_acc", { institutionName,accountName,industry,bucketId })
}

export function retrieveAccount(accountId: number) {
    return invoke()<RetrievedAccount>("retrieve_account", { accountId })
}

export function createBucket(bucketName: string, bucketColor: string) {
    return invoke()<number>("create_bucket", { bucketName,bucketColor })
}

export function recolorBucket(bucketId: number, bucketColor: string) {
    return invoke()<number>("recolor_bucket", { bucketId,bucketColor })
}

export function renameBucket(bucketId: number, bucketName: string) {
    return invoke()<number>("rename_bucket", { bucketId,bucketName })
}

export function deleteBucket(bucketId: number) {
    return invoke()<number>("delete_bucket", { bucketId })
}

export function getUserBuckets() {
    return invoke()<RetrievedBucket[]>("get_user_buckets")
}

export type RetrievedBucket = { id: number; name: string; color: string }
export type RetrievedSecretAccount = { id: number; created_at: string; account_name: string; mode: Mode; industry: Industry; two_factor_auth: boolean; recovery: string | null; bucket_name: string; bucket_color: string; institution_name: string; password: string }
export type Mode = "Secure" | "SuperSecure" | "LegacySecure" | "SSO"
export type RetrievedAccount = { RetrievedSecretAccount: RetrievedSecretAccount }
export type Industry = "Tech" | "Games" | "Social" | "Finance" | "Shopping" | "Science" | "Other"
