/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function signin(email: string, password: string) {
    return invoke()<null>("signin", { email,password })
}

export function signup(email: string, username: string, password: string) {
    return invoke()<null>("signup", { email,username,password })
}

export function isAuthenticated() {
    return invoke()<boolean>("is_authenticated")
}


