//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::account::Entity as Account;
pub use super::bucket::Entity as Bucket;
pub use super::institution::Entity as Institution;
pub use super::user::Entity as User;
