//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "industry")]
pub enum Industry {
    #[sea_orm(string_value = "Finance")]
    Finance,
    #[sea_orm(string_value = "Games")]
    Games,
    #[sea_orm(string_value = "Other")]
    Other,
    #[sea_orm(string_value = "Science")]
    Science,
    #[sea_orm(string_value = "Shopping")]
    Shopping,
    #[sea_orm(string_value = "Social")]
    Social,
    #[sea_orm(string_value = "Tech")]
    Tech,
}
