name: Show Me the S3cr3tz
on: push

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        run: |
          echo $TAURI_KEY_PASSWORD >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
