name: 'publish'

on:
  push:
    branches:
      - main
  workflow_dispatch:

# `tauri-action` can also upload app bundles to an existing GitHub release.
# This workflow uses different actions to create and publish the release.
# `tauri-action` will only build and upload the app bundles to the specified release.

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: create release
        id: create-release
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `app-v${process.env.PACKAGE_VERSION}`,
              name: `My-Passwords v${process.env.PACKAGE_VERSION}`,
              body: 'Take a look at the assets to download and install this app.
                      - [Windows: `My-Passwords_${process.env.PACKAGE_VERSION}_x64_en-US.msi`](https://github.com/relativityhd/My-Passwords/releases/download/app-v${process.env.PACKAGE_VERSION}/My-Passwords_${process.env.PACKAGE_VERSION}_x64_en-US.msi)
                      - [MacOS (Intel): `My-Passwords_${process.env.PACKAGE_VERSION}_x64.dmg`](https://github.com/relativityhd/My-Passwords/releases/download/app-v${process.env.PACKAGE_VERSION}/My-Passwords_${process.env.PACKAGE_VERSION}_x64.dmg)
                      - [MacOS (ARM): `
                      My-Passwords_${process.env.PACKAGE_VERSION}_aarch64.dmg `](https://github.com/relativityhd/My-Passwords/releases/download/app-v${process.env.PACKAGE_VERSION}/My-Passwords_${process.env.PACKAGE_VERSION}_aarch64.dmg)
                      - [Linux (AppImage): `my-passwords_${process.env.PACKAGE_VERSION}_amd64.AppImage`](https://github.com/relativityhd/My-Passwords/releases/download/app-v${process.env.PACKAGE_VERSION}/my-passwords_${process.env.PACKAGE_VERSION}_amd64.AppImage)
                      - [Debian: `my-passwords_${process.env.PACKAGE_VERSION}_amd64.deb`](https://github.com/relativityhd/My-Passwords/releases/download/app-v${process.env.PACKAGE_VERSION}/my-passwords_${process.env.PACKAGE_VERSION}_amd64.deb)
                      - [Fedora / CentOS / RHEL : `my-passwords-${process.env.PACKAGE_VERSION}-1.x86_64.rpm`](https://github.com/relativityhd/My-Passwords/releases/download/app-v${process.env.PACKAGE_VERSION}/my-passwords-${process.env.PACKAGE_VERSION}-1.x86_64.rpm)',
              draft: true,
              prerelease: false
            })
            return data.id

  build-tauri:
    needs: create-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@1.79.0
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: install frontend dependencies
        run: yarn install # change this to npm, pnpm or bun depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          args: ${{ matrix.args }}

  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [create-release, build-tauri]

    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@v7
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })
